### PR TITLE
Upgrade to v1.17.2

### PR DESCRIPTION
**Pull request by seamuslee001**

### CODE REVIEW

**Review by johntwyman — APPROVED** [review]
Good to see bug fixes _and_ feature inclusions

**Comment by andrew-cormick-dockery** [comment]
How are we currently using this?

**Comment by johntwyman** [comment]
> How are we currently using this?

CiviRules is being used for automated email engagement chains. CiviRules uses this extension to send the emails.

**Comment by andrew-cormick-dockery** [comment]
OK.  Theoretically a minor version release shouldn't break any existing CiviRules and you're happy with it, so I'm not going to block it.

**Review by andrew-cormick-dockery — APPROVED** [review]

**Pull request merged**
